---
- name: Clone one or more volumes and mount the clone on original junction path
  hosts: "{{ ansible_limit }}"
  gather_facts: no
  connection: 'local'
  collections:
    - netapp.ontap
  vars: 
    clone_and_mount_volumes: 
      svms: ['svm1'] 
      vols: ['test', 'test2']
      fields: ['nas.path','aggregates']
  tasks:
  - name: Get volume(s) by name from svm(s) specified 
    include_tasks: tasks/ontap_get_cluster_info_rest.yml
    vars: 
      gather_subset: ['storage/volumes']
      parameters: 
        name: "{{ clone_and_mount_volumes.vols | join(',')}}"
        svm: "{{ clone_and_mount_volumes.svms  | join(',')}}"
      fields: "{{ clone_and_mount_volumes.fields }}"
  - name: Examine results
    debug: 
      var: ontap_rest_info['storage/volumes']['records']
  # 1. Create a snapshot
  # 2. Unmount the volume
  # 3. Clone the volume 
  # 4. Mount the clone with the original volume's junction path
