---
- name: Upgrade firmware 
  hosts: "{{ ansible_limit }}"
  gather_facts: no
  connection: 'local'
  collections:
    - netapp.ontap
  vars_files: 
    - http_server
  tasks:
  - name: Check url
    debug: 
      var: http_server_url
    run_once: true
  - name: Update all.zip, confirm successful download
    netapp.ontap.na_ontap_firmware_upgrade:
      state: present
      package_url: "{{ http_server_url }}/all.zip"
      hostname: "{{ ontap_hostname }}"
      username: "{{ ontap_username }}"
      password: "{{ ontap_password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
